/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giayhub.Dashboard.main;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import giayhub.Dashboard.event.EventMenu;
import giayhub.Dashboard.form.CustomerManagement;
import giayhub.Dashboard.form.DashboardManagement;
import giayhub.Dashboard.form.InvoiceManagement;
import giayhub.Dashboard.form.LicenseManagement;
import giayhub.Dashboard.form.OrderManagement;
import giayhub.Dashboard.form.ProductManagement;
import giayhub.Dashboard.form.StatisticalManagement;
import giayhub.Dashboard.form.SuppliersManagemnt;
import giayhub.Views.LoginForm;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author phong
 */
public class Main extends javax.swing.JFrame {

    public boolean isDarkMode;
    
    public Main(String username) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));

        EventMenu event = new EventMenu() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    lblDanhMuc.setText("Tổng quan");
                    showForm(new DashboardManagement());
                } else if (index == 1) {
                    showForm(new ProductManagement());
                    lblDanhMuc.setText("Quản lý sản phẩm");
                } else if (index == 2) {
                    lblDanhMuc.setText("Quản lý bán hàng");
                    showForm(new InvoiceManagement());
                } else if (index == 3) {
                    lblDanhMuc.setText("Quản lý hóa đơn");
                    showForm(new OrderManagement());
                } else if (index == 4) {
                    showForm(new CustomerManagement());
                    lblDanhMuc.setText("Quản lý khách hàng");
                } else if (index == 5) {
                    lblDanhMuc.setText("Thống kê");
                    showForm(new StatisticalManagement());
                } else if (index == 6) {
                    showForm(new SuppliersManagemnt());
                    lblDanhMuc.setText("Quản lý nhà cung cấp");
                } else if (index == 7) {
                    lblDanhMuc.setText("Giấy phép");
                    showForm(new LicenseManagement());
                } else if (index == 8) {
                    int o = JOptionPane.showConfirmDialog(null, "Đăng xuất khỏi tài khoản của bạn?");
                    if (o == JOptionPane.YES_OPTION) {
                        dispose();
                        new LoginForm().setVisible(true);
                    }
                } else {

                }
            }
        };
        lblDanhMuc.setText("Xin chào: " + username + "  |  " + "GiàyHub chúc bạn một ngày tốt lành!");
        lblUsername.setText(username);
        menu1.initMenu(event);
    }

    private void showForm(JPanel panel) {
        body.removeAll();
        body.add(panel, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
        SwingUtilities.updateComponentTreeUI(body); // Cập nhật giao diện
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new giayhub.Dashboard.swing.RoundPanel();
        header1 = new giayhub.Dashboard.component.Header();
        roundPanel3 = new giayhub.Dashboard.swing.RoundPanel();
        lblLogo = new javax.swing.JLabel();
        lblDanhMuc = new javax.swing.JLabel();
        buttonBadges2 = new giayhub.Dashboard.swing.ButtonBadges();
        roundPanel2 = new giayhub.Dashboard.swing.RoundPanel();
        imageAvatar1 = new giayhub.Dashboard.swing.ImageAvatar();
        lblUsername = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        menu1 = new giayhub.Dashboard.component.Menu();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        roundPanel1.setBackground(new java.awt.Color(234, 239, 250));
        roundPanel1.setToolTipText("");

        header1.setBackground(new java.awt.Color(255, 255, 255));
        header1.setPreferredSize(new java.awt.Dimension(1371, 76));

        roundPanel3.setBackground(new java.awt.Color(239, 239, 239));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giayhub/Images/logo-nho-3.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblLogo)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        lblDanhMuc.setFont(new java.awt.Font("Inter 24pt", 1, 24)); // NOI18N
        lblDanhMuc.setForeground(new java.awt.Color(255, 153, 0));
        lblDanhMuc.setText("jLabel1");

        buttonBadges2.setBackground(new java.awt.Color(255, 153, 0));
        buttonBadges2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giayhub/Images/darkMode.png"))); // NOI18N
        buttonBadges2.setToolTipText("");
        buttonBadges2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBadges2MouseClicked(evt);
            }
        });
        buttonBadges2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header1Layout.createSequentialGroup()
                .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBadges2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header1Layout.createSequentialGroup()
                        .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(header1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(buttonBadges2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblDanhMuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));

        imageAvatar1.setForeground(new java.awt.Color(255, 153, 0));
        imageAvatar1.setBorderSize(3);
        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giayhub/Images/conMeo.jpg")));

        lblUsername.setFont(new java.awt.Font("Inter 24pt", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 153, 0));
        lblUsername.setText("Username");

        lblAdmin.setFont(new java.awt.Font("Inter 24pt", 0, 14)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(0, 0, 0));
        lblAdmin.setText("Admin");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblAdmin))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblUsername)
                        .addGap(18, 18, 18)
                        .addComponent(lblAdmin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        body.setOpaque(false);
        body.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBadges2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBadges2ActionPerformed

    private void buttonBadges2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBadges2MouseClicked
        try {
            if (isDarkMode) {
                UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
                buttonBadges2.setIcon(new ImageIcon(getClass().getResource("/giayhub/Images/lightMode.png")));
                header1.setBackground(new Color(255,255,255));
                roundPanel1.setBackground(new Color(234, 239, 250));
            } else if (!isDarkMode) {
                buttonBadges2.setIcon(new ImageIcon(getClass().getResource("/giayhub/Images/darkMode.png")));
                UIManager.setLookAndFeel(new FlatArcDarkOrangeIJTheme());
                header1.setBackground(new Color(56, 60, 74));
                roundPanel1.setBackground(new Color(56, 60, 74));
            }
            isDarkMode = !isDarkMode;
            
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonBadges2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private giayhub.Dashboard.swing.ButtonBadges buttonBadges2;
    private giayhub.Dashboard.component.Header header1;
    private giayhub.Dashboard.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsername;
    private giayhub.Dashboard.component.Menu menu1;
    private giayhub.Dashboard.swing.RoundPanel roundPanel1;
    private giayhub.Dashboard.swing.RoundPanel roundPanel2;
    private giayhub.Dashboard.swing.RoundPanel roundPanel3;
    // End of variables declaration//GEN-END:variables
}
