/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package giayhub.Dashboard.form;

import giayhub.DAO.StatisticsDAO;
import giayhub.Dashboard.form.blankchart.chart.ModelChart;
import giayhub.Models.Statics;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author phong
 */
public class StatisticalManagement extends javax.swing.JPanel {

    private StatisticsDAO service = new StatisticsDAO();

    public StatisticalManagement() {
        initComponents();
        chart.setBackground(new Color(250, 250, 250));
        chart.addLegend("Doanh Thu", new Color(245, 189, 135));
        chart.addLegend("Sản Phẩm", new Color(135, 189, 245));
        chart.addLegend("Đơn Hàng", new Color(189, 135, 245));

        for (Statics doanhThu : service.getThongKe(3, 2025)) {
            lblThang.setText("<html>Biểu đồ thống kê doanh thu <font color='#FF9900'>tháng "
                    + doanhThu.getThang() + "</font> <font color='#FF9900'>năm "
                    + doanhThu.getNam() + "</font></html>");
            chart.addData(new ModelChart("Tháng " + doanhThu.getThang(),
                    new double[]{doanhThu.getTongDoanhThu() * 0.001,
                        doanhThu.getTongSoSPDaBan(),
                        doanhThu.getTongSoDonHang()}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new giayhub.Dashboard.swing.RoundPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblThang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbNam = new javax.swing.JComboBox<>();
        cbThang = new javax.swing.JComboBox<>();
        btnLocDuLieu = new javax.swing.JButton();
        chart = new giayhub.Dashboard.form.blankchart.chart.Chart();

        setPreferredSize(new java.awt.Dimension(1101, 651));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblThang.setFont(new java.awt.Font("Inter 24pt", 1, 18)); // NOI18N
        lblThang.setForeground(new java.awt.Color(0, 0, 0));
        lblThang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThang.setText("Thanh Tùng số 1, Quang Duy đẳng cấp, Thái Phong okvip, Hải Đăng quá ok, Trần Anh Cường trùm FPT");

        jLabel1.setFont(new java.awt.Font("Inter 24pt", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Doanh thu tháng này thế nào?");

        jLabel2.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jLabel2.setText("Xem ngay:");

        cbNam.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        cbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025" }));
        cbNam.setSelectedIndex(5);

        cbThang.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        btnLocDuLieu.setText("Lọc dữ liệu");
        btnLocDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocDuLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThang, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocDuLieu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocDuLieu))
                .addGap(43, 43, 43)
                .addComponent(lblThang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Biểu đồ", jPanel1);

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocDuLieuActionPerformed
        chart.clearData();
        List<Statics> thongKeList = service.getThongKe(
                Integer.parseInt(cbThang.getSelectedItem().toString()),
                Integer.parseInt(cbNam.getSelectedItem().toString()));
        if (!thongKeList.isEmpty()) {
            // Chỉ cập nhật tiêu đề một lần với dữ liệu của tháng đầu tiên
            Statics first = thongKeList.get(0);
            lblThang.setText("<html>Biểu đồ thống kê doanh thu <font color='#FF9900'>tháng "
                    + first.getThang() + "</font> <font color='#FF9900'>năm "
                    + first.getNam() + "</font></html>");

            // Thêm dữ liệu vào biểu đồ
            for (Statics doanhThu : thongKeList) {
                chart.addData(new ModelChart("Tháng " + doanhThu.getThang(),
                        new double[]{doanhThu.getTongDoanhThu() * 0.001,
                            doanhThu.getTongSoSPDaBan(),
                            doanhThu.getTongSoDonHang()}));
            }
        } else {
            lblThang.setText("Không có dữ liệu thống kê!");
        }
    }//GEN-LAST:event_btnLocDuLieuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocDuLieu;
    private javax.swing.JComboBox<String> cbNam;
    private javax.swing.JComboBox<String> cbThang;
    private giayhub.Dashboard.form.blankchart.chart.Chart chart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblThang;
    private giayhub.Dashboard.swing.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables

}
